def funcionPrueba(a, b) -> int:
    print(f'La suma es:\n{a+b}')
    return(a+b)
    # return(a+b)

assert funcionPrueba(1,2) == 2, 'Error al sumar'


